### ISSUE TITLE
What is open source?

### ISSUE THREAD

**Issue by JeromeMartinez** [FrictionalGames/AmnesiaTheDarkDescent#7]
The [announcement](https://frictionalgames.com/2020-09-amnesia-is-now-open-source/) indicates "Amnesia is now open source!" but I don't find any legal reference to Amnesia assets.
there is a classic misunderstanding between a "game" and a "game engine" when people move to (some) open source, so it would be great to be explicit and/or not misleading.

Is Amnesia now open source or is Amnesia engine open source?
In other words, if we bought (looks like the assets are not in the repo) the game so if we have Amnesia assets (all non "code" stuff: visual or audio parts) in some way, are they covered by the GPLv3 license?

(no criticism whatever is the answer, just for knowing the exact legal terms, as it seems that the announcement, hinting that the game is open source, and the content of the repo, hinting that the game engine is open source, are not same; what whatever the answer such announcement is great)

**Comment by Mudbill** [comment]
HPL2 is open source, and as they say "free as in free speech, not free beer."
Amnesia TDD and AMFP are also open source and free (speech).

The assets for the games are still owned by FG and are not free. Thus you can do whatever you like with the source code from these repositories, but realistically you won't be able to run everything if you don't also have the legal assets from owning the game they are meant for. As they clarified, the game is not free to access by anyone, since having only the source code for the game is not the complete project required to actually _play_ the game.

If you're confused about what the difference is between HPL2 and "Amnesia" – well, it's kind of ambiguous. But HPL2 deals with the code on an engine level, not specific to the game, and Amnesia's code deals with the features that are specific to the game and utilizes the engine features from HPL2. They are very much coupled, but you can think of HPL2 being a dependency of Amnesia, however HPL2 is not dependent on Amnesia.

Does that clear anything up?

**Comment by JeromeMartinez** [comment]
> Does that clear anything up?

Yes, it does.

Just a remark:

> HPL2 is open source, and as they say "free as in free speech, not free beer."

From your clarification, it is a wrong sentence, as you indicate that HPL2 assets are not open source, also in the sentence "free as in free speech" (if I buy the assets, I can not use them as a free speech).
HPL2 engine is open source.

> Edit: Just to quote the announcement:

IMO the quoted sentence is misleading, "It just means that people are free to use the source however they want as long as they adhere to the GPL3 licence." but you don't put the assets source in GPLv3, so it was not clear about what is open source, especially with the title of the page ("Amnesia" with assets removed is not Amnesia, it is Amnesia engine, as a car is not open source just because the car engine is open source). It is misleading because the title indicates "the game is open source" and later you indicate "warning the game is actually not open source, only the game engine" (I don't talk about $, just free speech).

Again, not a criticism, just clarification about what is open source and what is not (game engine is open source, game assets are not open source "free as in free speech, not free beer."), and it is common to have a game **engine** open source (which is already great) and not the corresponding game **assets**.

**Comment by Mudbill** [comment]
> it is common to have a game engine open source (which is already great) and not the corresponding game assets.

I believe this is exactly what they mean. I understand the confusion, hence I added that last statement:

> "Amnesia" is both a game and a project. Consider the project free, but not the game.

So while the game is not open-source, the code that runs the game is, as well as the underlying engine. Had it only been HPL2 that was open-source, we would not have any game specific source code. An example of this is the code that decides the AI for the grunt – this is "Amnesia" code, not HPL2 code. The HPL2 code would only give us "agents" and "what AIs can do" but not "what they actually do."

They did the same thing with Penumbra and HPL1, although in that case they separated them into two repositories instead of including HPL2 inside each Amnesia repository. There is one repo for HPL1 which can be compiled independently from the repo of PenumbraOverture, but you likely want both together.

**Comment by juliosueiras** [comment]
btw, to throw my two cents here, the wording on the README should probably reflect that, since most other similar repo(like diablo one) have a note indicating that it would still need the assets package/data to actually run the game, where as in this README, it start with "Here is everything you need to build Amnesia: The Dark Descent." which give me the impression that this is the full game (code+images, etc) 

P.S. this is why I was confused of how the repo was so small in term of size or though that it was using lfs or something(but didn't see the linkage file)

**Comment by Mudbill** [comment]
Isn't it correct though? You can _build_ Amnesia, but you can't run it :D

**Comment by juliosueiras** [comment]
¯\_(ツ)_/¯ , I mean yea technically speaking, but would be a nice Note to have to dispel potential people who are looking to run the game without having the assets

**Comment by Mudbill** [comment]
Indeed, I wouldn't mind the README to be a bit clearer. It certainly could use some instructions as well, since not everything was quite "out of the box" as one might expect.

**Comment by Zipdox** [comment]
Read the license

**Comment by JeromeMartinez** [comment]
> Read the license

I know what is the GPLv3, thank you. Your answer is far from being constructive, and out of topic.
The license is not the issue, the issue is a question about what part of "Amnesia" has the license (the announcement says that "Amnesia" is open source, but the repo has only a part of "Amnesia" so there is a mismatch between the announcement, with an unclear warning as it is out of topic, and the reality).

In practice "Amnesia" assets don't have the open source ("as a free speech") license, only "Amnesia" engine, so reading the license would not help me for "Amnesia" (without "engine") as this license does not applies.

I wonder why is it so difficult to just be clear that "Amnesia" is still not open source but "Amnesia engine" (a part of "Amnesia") is now open source? No shame about that, just being clear.

**Comment by jkulawik** [comment]
Why would anything outside this repository be also open source?

**Comment by JeromeMartinez** [comment]
> Why would anything outside this repository be also open source?

Please fully read the first issue comment.
The important line is the link to the announcement, saying "Amnesia is now open source!"
I was looking for "Amnesia" repo and I found only this repo (which is not "Amnesia" repo, it is "Amnesia engine" repo), my question was always to know if the announcement is correct or not (and it seems it is not, else the fix would have been to put the assets in this repo), as I am interested in "Amnesia is now open source!" and not its engine only, that's all.

as @TiManGames thumbed up the comment, I guess that it is clear that the announcement is misleading, I get it, so Amnesia is not open source (but its engine is, which is already great, again, no critisism). Just sad to announce something not so true, I guess it is "marketing" stuff.

I guess that the announcement will not be fixed, I close the issue.
